### ISSUE TITLE
Problem in v2.0.0+ in Firefox, Safari and iOS companion app

### ISSUE THREAD

**Issue by HepoH3** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#130]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello, thank you for still working on this card.
Apparantly there is a problem with picking up the point / moving / resizing custom zone area in firefox browsers. In Chrome and Edge browsers that's working just fine.

Chrome:
![](https://puu.sh/IplAx/f3b6337f7e.png)
Firefox (can't set point):
![](https://puu.sh/IplBn/a2a61fac71.png)

### What version of a card has described problem?

v2.0.0

### What vacuum model do you have problems with?

STYJ02YM 

### What version of Home Assistant do you use?

2021.11.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
- type: custom:xiaomi-vacuum-map-card
    entity: vacuum.kraken
    map_source:
      camera: camera.vacuum_extractor_camera
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
    vacuum_platform: KrzysztofHajdamowicz/miio2
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught ReferenceError: TouchEvent is not defined
    _drag http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:181
    render http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:150
    handleEvent http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:31
```

**Comment by nickdos** [comment]
Seeing similar issues on Safari and Mac OS Companion app (v.2.0.1).

I can't change move or the size of manually added zones. I can't remove a zone via the `x` either. When the map is "unlocked" and I add a manual zone, when I try to move the newly created zone, the entire map moves and not the zone. If I lock  the map then nothing happens when trying to move the zone. Click and dragging does nothing.

Similarly on the iOS companion app I can't move, resize or remove a zone added via "Zone cleanup".

**Comment by Lyr3x** [comment]
Besides that I can also confirm that the bug exists in safari and the iOS/iPadOS I just want to state that the ROOM listing is also not working. In Chrome everything runs fine

**Comment by PiotrMachowski** [comment]
There are major improvements in `v2.0.2`, most of functionalities should work.

Remaining problem: selections are not mapped correctly when map is zoomed-in

**Comment by nickdos** [comment]
Just tested v2.0.2 and Safari is working now. 

However both the iOS and Mac OS companion apps still donot show the zones. I've forced the apps to reload a few times and still not zones showing. I even edited the config to change the card display a little and the changes appeared but still no zones.

**Comment by PiotrMachowski** [comment]
@nickdos can you check if any of new feature works on iOS/Mac to make yourself sure that they use the latest release? The easiest way to do it is to add `language` to config:
```yaml
type: custom:xiaomi-vacuum-map-card
language: it
...
```

**Comment by nickdos** [comment]
Hey @PiotrMachowski - tried that. Still no good on companion apps:

![image](https://user-images.githubusercontent.com/532845/142337635-22bd1e81-7f4d-4ba6-ab33-cd7eac4a715b.png)

vs Safari is OK:

![image](https://user-images.githubusercontent.com/532845/142337690-a88634da-bfba-4326-a520-b3466b76e5e4.png)

**Comment by PiotrMachowski** [comment]
@nickdos does it work on mobile safari?

**Comment by nickdos** [comment]
No, not working on Safari browser on iOS, either.

**Comment by Lyr3x** [comment]
After deleting the cache of the app the zones appear on my app but labels and icons not. I can also start the room cleaning

**Comment by PiotrMachowski** [comment]
@Lyr3x You can change URL in resources by adding `?v=v2.0.2`, it should solve caching problem

**Comment by Lyr3x** [comment]
I added ˋ/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js?v=v2.0.2ˋ that's not working either :) after a swipe down the zones are gone again

**Comment by PiotrMachowski** [comment]
If you use HACS then HACS should handle this case by itself... You can try removing and reinstalling the card

**Comment by Lyr3x** [comment]
I did, and already was on the latest version. But still in iOS zones, icons and texts are gone and only visible for a short time after clearing the frontend cache.

**Comment by cris1410** [comment]
Hi guys, I can confirm correct behavior on Safari on PC or MAC and still incorrect behavior on iOS web browsers.

**Comment by HepoH3** [comment]
@PiotrMachowski, from my side I can tell that problem gone in my Firefox browser, so appantly now this problem remain only on iOS.

**Comment by PiotrMachowski** [comment]
@HepoH3 there is still a problem with Firefox: pin & go doesn't work properly when zoomed-in.

**Comment by HepoH3** [comment]
> 
> 
> @HepoH3 there is still a problem with Firefox: pin & go doesn't work properly when zoomed-in.

Oh, indeed. I just locked map from zooming/moving and didn't notice that.

**Comment by StWiesi** [comment]
I am also having issues with Safari on MacOS. In Chrome everything works flawlessly. I am using selection of predefined zones, selected zones and pin and go - including icons and labels.

In Chrome, selection of predefined zones looks like this:

![Bildschirmfoto 2021-11-19 um 18 59 39](https://user-images.githubusercontent.com/29369564/142669743-41f64b28-a28a-461b-b2c8-f185d743c7e0.png)

In Safari, it looks like this with icons all being crunched together on the top left:

![Bildschirmfoto 2021-11-19 um 19 01 03](https://user-images.githubusercontent.com/29369564/142669892-f138d24a-99b5-4e4a-9eb2-00c4afa739ea.png)

Also, on Safari some other things don't work reliable - at least for me. Here are some steps to reproduce this:

1. Refresh website where the card is on
2. Zone selection is selected by default - don't touch it
3. Add a rectangle by pressing + button.
4. Size cannot be adjusted, rectangle cannot be deleted
5. Select predefined zone option - looks like the picture above with incorrectly located icons; zones can be selected though
6. Select Pin & Go - works fine.

If I refresh the website once more and add a zone as mentioned in step 2, but just move to Pin & Go right away, I cannot set any pin. If I then select predefined zones not only the icons are off, but also the labels:

![Bildschirmfoto 2021-11-19 um 19 12 48](https://user-images.githubusercontent.com/29369564/142671337-2e8e1ea3-6570-4221-8c3d-399dc68eecdd.png)

So, it seems that when I initially add a selection (which cannot be deleted or adjusted) and then select one of the other options, everything (except icons for predefined zones) works fine - even the adjusting of a selected zone if I go back to that option. If I don't add a selection in the beginning, almost nothing works properly.

**Comment by PiotrMachowski** [comment]
@HepoH3 @nickdos @Lyr3x @cris1410 @StWiesi 

Everything should be fixed in v2.0.3, can you confirm it?

**Comment by HepoH3** [comment]
> @HepoH3 @nickdos @Lyr3x @cris1410 @StWiesi
> 
> Everything should be fixed in v2.0.3, can you confirm it?

Yup, works in firefox on original scale and when scaled up and(or) moved map.

**Comment by Lyr3x** [comment]
iOS looks good now too. Thank you:)

**Comment by nickdos** [comment]
Hey @PiotrMachowski - looks good to me on both iOS and Mac companion apps. Great work fixing this 💪

**Comment by StWiesi** [comment]
Hey @PiotrMachowski,

almost everything works fine now. Pin & Go & predefined zones are not having any issues.
However, the (non-predefined) rectangular zone selection is not adjustable/movable/deletable if it is the first thing I do when loading the card.
After using predefined zones or pin & go, the rectangular selection works fine again.

**Comment by Lyr3x** [comment]
On my iPhone and iPad the zoned cleanup where you just set the rectangle, is working fine. I can move and resize it with no issues. Not using the Mac app though!

**Comment by PiotrMachowski** [comment]
@StWiesi is there anything in browser's console?

**Comment by StWiesi** [comment]
> @StWiesi is there anything in browser's console?

unfortunately, no. Just the information around what cards and version I am using. Since "XIAOMI-VACUUM-MAP-CARD 
  Version v2.0.3" is displayed it should be the updated version already.

**Comment by PiotrMachowski** [comment]
Can you show a screen recording of the problem?

**Comment by StWiesi** [comment]
Sure - you can see it here:

https://user-images.githubusercontent.com/29369564/142850746-59d603ec-b24b-4309-90b4-5cb542a47ed5.mov

**Comment by PiotrMachowski** [comment]
Can you try disabling `map_locked` and try again?

**Comment by PiotrMachowski** [comment]
@StWiesi any change in v2.0.5?

**Comment by StWiesi** [comment]
Hey @PiotrMachowski,

unfortunately, no change in behavior.

**Comment by cris1410** [comment]
Hi,

I can confirm that v2.0.5 works for mi on 98%.
Only issue is exactly what @StWiesi reported " _rectangular zone selection is not adjustable/movable/deletable if it is the first thing I do when loading the card. After using predefined zones or pin & go, the rectangular selection works fine again_."

But this is not big limitation for me.
Thank you @PiotrMachowski

**Comment by PiotrMachowski** [comment]
@StWiesi @cris1410 v2.0.6 should fix the last 2% 🙂

**Comment by StWiesi** [comment]
Hey @PiotrMachowski,

unfortunately, still the same issues as before 🙈

**Comment by PiotrMachowski** [comment]
@StWiesi Can you try again in incognito mode?

**Comment by StWiesi** [comment]
Still the same behavior - I tried it several times always opening a new private window in Safari.

**Comment by PiotrMachowski** [comment]
@StWiesi that's really weird, it works on my instance with iPhone 6s... Is there anything in browser's console? Does the map blink after switching "locked mode"? Is the map restored to default position after locking?

**Comment by StWiesi** [comment]
Hey @PiotrMachowski,

I made another video to better illustrate it. I am using a Macbook Pro with macOS Big Sur 11.6 and Safari  15.1

Is it working for you @cris1410?

https://user-images.githubusercontent.com/29369564/143618929-0c9d456a-6c21-4248-aad0-1a20d85940e0.mov

**Comment by PiotrMachowski** [comment]
Can you check browser's console for any errors? It should also contain a badge with currently loaded version (to confirm that everything is loaded correctly)

**Comment by StWiesi** [comment]
no errors at all - v2.0.7 is loaded.

**Comment by PiotrMachowski** [comment]
Ok, I'm out of ideas... It works perfectly well on all my devices

**Comment by PiotrMachowski** [comment]
I have created a dedicated issue for this case: #230

**Comment by cris1410** [comment]
> @StWiesi @cris1410 v2.0.6 should fix the last 2% 🙂 Can you check it out?

Still same behaviour. But as I said, its not big deal. just need to switch either to Pin&Go or Zone list and then back to Zone cleanup.

**Comment by PiotrMachowski** [comment]
@cris1410 @StWiesi You can also try to change order of map modes to make "Zone cleanup" a non-default one

**Comment by StWiesi** [comment]
> @cris1410 @StWiesi You can also try to change order of map modes to make "Zone cleanup" a non-default one

That's what I did. Makes everything work perfectly for me :)
