### ISSUE TITLE
"Internal" repeats type doesn't work

### ISSUE THREAD

**Issue by Enzokot** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#161]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

"Internal" repeats type doesn't work
![image](https://user-images.githubusercontent.com/43236573/142048426-c8c52f3c-6a48-4ef6-b8e4-650a66f1bcd4.png)

### What version of a card has described problem?

2.0.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

core-2021.11.4

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
- name: Rooms
  icon: mdi:floor-plan
  selection_type: ROOM
  max_selections: 8
  repeats_type: INTERNAL
  max_repeats: 3
  service_call_schema:
    service: script.vacuum_follow_path #create notification for debug
    service_data:
      path: "[[selection]]"
      entity_id: "[[entity_id]]"
```

**Comment by PiotrMachowski** [comment]
Actually it works, just not with `selection_type: ROOM`. I thought it will be useless, so I have skipped it. Anyway, I will add it in the next version 👍

**Comment by Enzokot** [comment]
As a suggestion. May be repeat count for each room?

**Comment by PiotrMachowski** [comment]
Separate repeat counter for each room is a tricky thing to do, maybe someday 🙂 Right now I can add a common counter for all rooms

**Comment by PiotrMachowski** [comment]
Resolved in v2.0.2

**Comment by Enzokot** [comment]
Thanks!

**Comment by Mr-Groch** [comment]
I think it still doesn't work...

My conf:
```
map_modes:
  - template: vacuum_clean_segment
    repeats_type: INTERNAL
    max_repeats: 3
    predefined_selections:
```

When I select room and set repeat >1 it stills clean that room once...

**Comment by PiotrMachowski** [comment]
@Mr-Groch the issue was not about this situation. Rooms need special treatment to work with this card, this issue was about unifying current approach:

`repeats_type: INTERNAL` should append repeats to `[[selection]]`, e.g. with selected rooms 10 and 15 + 2 repeats it now looks like this: `[10, 15, 2]`

to make make it work by default it should be like this: `[10, 10, 15, 15]`. I will add it as well, but this will require a new value for `repeats_type`

**Comment by Mr-Groch** [comment]
OK, it is possible then to use repeat with rooms currently?

**Comment by PiotrMachowski** [comment]
@Mr-Groch no, it is not possible at this moment. I will add it in the future

**Comment by Mr-Groch** [comment]
@PiotrMachowski OK, so i'll wait then :)

I've checked yours theory of sending doubled room ids in vacuum_clean_segment service:

```
service: xiaomi_miio.vacuum_clean_segment
data:
  segments: [17, 17]
```

And it works like selecting repeat 2 in Xiaomi Home app - vacuum cleans room 2 times, each time in different pattern, so it is great :)

**Comment by Heisenberg2980** [comment]
Another vote for this request, being able to use repeat with rooms will be really useful.

P.D.: @PiotrMachowski amazing work you have done in this update, really impressive!!

**Comment by Heisenberg2980** [comment]
@PiotrMachowski should we open a new issue for this extra functionality of "repeat rooms" or are you tracking it anywhere else?

**Comment by PiotrMachowski** [comment]
@Heisenberg2980 I have it on my "TODO" list, but you can open a new issue if you want to.

There is a solution that lets you have repeat for rooms right now: [example](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/204)

**Comment by Heisenberg2980** [comment]
Really? I will check it out!!

**Comment by Heisenberg2980** [comment]
It works like a charm, thank you!!
