### ISSUE TITLE
Ecovacs Deebot issues

### ISSUE THREAD

**Issue by Anashost** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#600]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hey @PiotrMachowski 
I've an ecovacs deebot N8 pro, which i integrated using Deebot 4 Home assistant, and working fine. I found about your really good looking UI integration but sadly some of the features doesn't work:

- number of cleans cycles in Room cleaning (x1 - x2) does nothing.

- zone cleaning doesn't work, so drawning a rectangle on the map, creates an (outside the map) rectangle in the deebot official app, and deebot returns to base.

- Predefined zone cleaning also doesn't work, whether i get the coordinates using your integration or according to Deebot 4 home assistant docs @edenhaus  , i get this error:
```
Failed to call service xiaomi_miio/vacuum_clean_zone. Service not
found.
``

### What version of a card has described problem?

v2.2.0

### What was the last working version card?

None

### What vacuum model do you have problems with?

Ecovacs Deebot N8 Pro

### Which integration do you use to control your vacuum (link)?

https://github.com/DeebotUniverse/Deebot-4-Home-Assistant

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

2023.5.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.windy
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: camera.windy_live_map
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 5
        icon:
          name: mdi:sofa
          x: -5900
          'y': -8000
      - id: 0
        icon:
          name: mdi:sofa
          x: -5800
          'y': 2500
      - id: 1
        icon:
          name: mdi:bed
          x: -15200
          'y': 2000
      - id: 4
        icon:
          name: mdi:toilet
          x: -12500
          'y': -7500
      - id: 2
        icon:
          name: mdi:knife
          x: -12000
          'y': -17500
      - id: 3
        icon:
          name: mdi:door
          x: -3900
          'y': -15500
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 239
            - 184
            - 1336
            - 665
        icon:
          name: mdi:rectangle
          x: -5800
          'y': 2500

```
```


### Javascript errors shown in the browser's console (if applicable)

_No response_

### Additional information

_No response_

**Comment by PiotrMachowski** [comment]
Can you also add a snapshot (created using `camera.snapshot` service - to keep the same resolution as original map image) of camera and a screenshot from the app with an invalid zone?

**Comment by Anashost** [comment]
Never done something like that 😅 i will try once I'm on my PC.

**Comment by Anashost** [comment]
- Here's the snapshot from camera.snapshot:
 
![snapshot](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/aaf4308d-eb27-4d39-b9b7-fbfdd3d134d8)
***
- screenshot from the official app (when zone created in the official app).
  Coordinates:
  [[198, 1911, 1332, 781]]

![Screenshot_20230603_173035_ECOVACS HOME](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/65a1ccbf-82f3-4681-b7cd-6db38275513a)
***
- screenshot from the official app (when zone created in HA vacuum card).
  Coordinates:
  [[-8212, 439, -4929, 3517]]
  (The coordinates are so different as you can see)

![Screenshot_20230603_181402_ECOVACS HOME](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/d6f6a897-a136-4b2d-8d30-69348b51a93a)

This is how it looks in the vacuum card:
![Screenshot_20230603_182621_Home Assistant](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/249a0a30-859b-4f01-ad24-7d7a6ccbe7ff)


I hope that can help debugging the issues.

**Comment by PiotrMachowski** [comment]
Great, thank you!

**Comment by PiotrMachowski** [comment]
I have investigated your problems and:
 - repeats: the card works correctly, so the problem must be in the integration
 - zone cleaning: it looks like the calibration is incorrect (@edenhaus are you sure about static calibration you have sent?)
 - predefined zone cleaning: fixed on dev branch

**Comment by Anashost** [comment]
Thanks, i will wait for the next release/beta to test predefined zone cleaning. But zone cleaning is what i really care about, as i use it a lot, so it would be nice if it works.

**Comment by PiotrMachowski** [comment]
> * This is the entity_id for repeats:
>   `number.VACUUM-NAME_clean_count`
>   Which works in @edenhaus integration.

According to the [documentation](https://deebot.readthedocs.io/integrations/home-assistant/examples/commands/#clean-only-certain-rooms) `cleanings` parameter should work as well



> * When i use the coordinates that i generate...

Does this version work as well?
```yaml
service: vacuum.send_command
target:
  entity_id: vacuum.windy
data:
  command: custom_area
  params:
    coordinates: 198, 781, 1332, 1911
```


You can try to use following cofig (you have to adjust coordinates of icons/zones):
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.windy
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: camera.windy_live_map
map_locked: true
two_finger_pan: true
calibration_source:
  calibration_points:
    - vacuum:
        x: 198
        y: 781
      map:
        x: 240
        y: 401
    - vacuum:
        x: 198
        y: 1991
      map:
        x: 240
        y: 469
    - vacuum:
        x: 1332
        y: 1991
      map:
        x: 310
        y: 469
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    ...
```

**Comment by PiotrMachowski** [comment]
Predefined zone cleaning fixed in v2.2.1

**Comment by Anashost** [comment]
Thanks boss, will try in the morning, otherwise the neighbors will call the police.

**Comment by Anashost** [comment]
Sorry @PiotrMachowski if I'm becoming a little bit of a headache 😅, so here we go.

> Does this version work as well?
> 
> ```yaml
> service: vacuum.send_command
> target:
>   entity_id: vacuum.windy
> data:
>   command: custom_area
>   params:
>     coordinates: 198, 781, 1332, 1911
> ```
Yes it worked like this too.

Predefined Zone cleaning now works 👌🏻 but as Zone cleaning still doesn't create zones correctly, still can't use it.

Current issues:

- when i add the calibration points you provided to the card, Rooms icons in "Room cleaning" dissappears from the map.

- So, Zone cleaning still creates off location rectangles (im using the calibration points you provided).
Examples:

  Coordinates: [[-375, -3164, 1486, -2014]]
  ![20230605_124614](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/4eb90576-0111-4089-befa-4f70612023c6)
  ***
  Coordinates:  [[-2511, -6174, -920, -4845]]
  ![20230605_125127](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/c593762a-1f0a-4cba-8646-8b9bacabe3e8)

  ***
  Coordinates:  [[-3002, -468, -1453, 724]]
  ![20230605_125032](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/421ba1f5-5e6d-4be8-93e8-40dbce4be83e)

  ***
  Coordinates: [[-77, 179, 1557, 1670]]
  ![20230605_124524](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/2f6c0c8b-d397-431a-9b3a-ec0fdd6a1981)

***
- Repeats (which still doesn't work) can be specified only in Room cleaning, as you can see:
  ![20230605_130507](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/41167157/950325d3-f8ff-4998-a7b0-227ff46e5a8e)

**Comment by PiotrMachowski** [comment]
> Repeats (which still doesn't work) can be specified only in Room cleaning, as you can see:

Zone cleaning doesn't have a "cleanings" parameter in the service call, so it is not available to select here.

Ok, so what I need are 4 sets of coordinates made for the same zone (marked on the map):
 - one retrieved from the vacuum - the "correct" ones
 - one retrieved from the card with calibration points I have sent above
 - one retrieved from the card with no `calibration_source` config
 - one retrieved from the card with following `calibration_source` config:
   ```yaml
   calibration_source:
     identity: true
   ``` 

Such data should make it possible to create a calibration for you (and possibly all other Ecovacs vacuums)

**Comment by PiotrMachowski** [comment]
Can you try these ones?
```yaml
        - vacuum:
            x: 358
            y: 3388
          map:
            x: 249
            y: 312
        - vacuum:
            x: 358
            y: 2508
          map:
            x: 249
            y: 365
        - vacuum:
            x: 1890
            y: 2508
          map:
            x: 342
            y: 365
```

**Comment by Anashost** [comment]
@PiotrMachowski 
very very nice, it's creating Zones perfectly now, really big Thanks for your work.

Final question 😅 is there an easy way to create outlines for the rooms, as getting the coordinates from the card gives me something like this:
`[[-611, -307, 1873, 3376]]`

While i need something like this for the outlines to work:
`[[1900, -805],[-700, -805],[-700, 3550],[1900, 3550]]`

and, what about if the room not a rectangle, but a more complex shape 🤔

**Comment by PiotrMachowski** [comment]
To get outline you have to change vacuum platform to "Setup integer", choose "Path" mode, mark an outline of the room and click "Copy selection"

**Comment by edenhaus** [comment]
> > * This is the entity_id for repeats:
> >   `number.VACUUM-NAME_clean_count`
> >   Which works in @edenhaus integration.
> 
> According to the [documentation](https://deebot.readthedocs.io/integrations/home-assistant/examples/commands/#clean-only-certain-rooms) `cleanings` parameter should work as well

@PiotrMachowski please use as described in the docs the `cleanings` parameter as this parameter is supported by all models and the clean count sensor only for a few newer models. For example my model is also not supporting it

**Comment by PiotrMachowski** [comment]
> Sorry for the late answer. 

@edenhaus No problem, I was aware that this might not be the final solution, but I have released it to be able to get more feedback about this functionality.

---

> But the calibration data was only meant for testing purposes by others as I currently don't have time to do it.

During calculation of calibration points I have found out following differences compared to your calibration:
- The "resolution" (vacuum diff/map diff) turned out to be 0.06 (compared to 0.02)
- The (0,0) point in vacuum coordinates maps to ~(230, 520) point in map coordinates (compared to 400, 400)
- The y axis is inverted - in the card if you're getting closer to the bottom then the y value increases, it seems to be the other way in the case of calibration that seems to work for @Anashost 

---

> @PiotrMachowski please use as described in the docs the `cleanings` parameter as this parameter is supported by all models and the clean count sensor only for a few newer models. For example my model is also not supporting it

The card uses this approach and it seems that it doesn't work (you can check out the code [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/src/model/generators/platform_templates/DeebotUniverse_Deebot-4-Home-Assistant.json#L20))

**Comment by Anashost** [comment]
> @Anashost could you provide the service call with repeats set to 2 (using card's "copy service call" functionality)?
> 
> In my case it looks the following way:
> 
> ```json
> {
>   "domain": "vacuum",
>   "service": "send_command",
>   "serviceData": {
>     "entity_id": "vacuum.test",
>     "command": "spot_area",
>     "params": {
>       "rooms": "0,1",
>       "cleanings": 2
>     }
>   }
> }
> ```

it looks the same as yours, but nothing happen as the entity id value stay 1
`number.VACUUM-NAME_clean_count`
```json
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.windy",
    "command": "spot_area",
    "params": {
      "rooms": "5",
      "cleanings": 2
    }
  }
}
```

**Comment by tantai251295** [comment]
@Anashost how you get "one retrieved from the vacuum - the "correct" ones" without app ?

**Comment by tantai251295** [comment]
@PiotrMachowski i have calibration my map to work correctly, but after I open the door and recleaning, images of map to change and my calibration not work correctly ?? how do i calibrate correctly no matter the size of the image ??

**Comment by PiotrMachowski** [comment]
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/321

**Comment by edenhaus** [comment]
The calibration data should be static. At least I use a static formula to generate the map.

> During calculation of calibration points I have found out following differences compared to your calibration:
> 
>     * The "resolution" (vacuum diff/map diff) turned out to be 0.06 (compared to 0.02)
> 
>     * The (0,0) point in vacuum coordinates maps to ~(230, 520) point in map coordinates (compared to 400, 400)
> 
>     * The y axis is inverted - in the card if you're getting closer to the bottom then the y value increases, it seems to be the other way in the case of calibration that seems to work for @Anashost

Hopefully I have time next week to give it a look.

@tantai251295 Can you please share me some screenshot with before/after

**Comment by jspayd** [comment]
Edit: Realized that this issue predates the SVG map, and has probably been solved. My issues are more likely related to https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/pull/715.

---

Original reply:

I'm having similar issues with my Deebot Ozmo T8, but what I've noticed is that calibration is browser-dependent. I normally use Firefox (macOS), but I originally calibrated using Chrome (also macOS) because I wanted to use the zone cleaning with identity calibration to get the map calibration points, and I couldn't even drag around the selection in Firefox with identity calibration.

The zone cleaning works great in Chrome when calibrated for Chrome, and it works great in Firefox when calibrated for Firefox, but the calibrations are different. I find that when I set the map points to 2.95x the calibration I created for Chrome, it works well for Firefox (actual correct value is slightly less than 2.95; I haven't found the perfect value). And the Home Assistant mobile app for iOS needs a different calibration than both Firefox and Chrome, but I haven't attempted to determine what that calibration is.

Is it possible this has something to do with the map being an SVG? Do other vacuum integrations that have SVG maps have this problem?

Calibration points that work for me in Chrome:
```yaml
  calibration_points:
    - vacuum:
        x: 600
        'y': -7750
      map:
        x: 82.5
        'y': 141
    - vacuum:
        x: -3900
        'y': 7850
      map:
        x: 42.5
        'y': 4
    - vacuum:
        x: 550
        'y': 8050
      map:
        x: 82
        'y': 3
    - vacuum:
        x: -6750
        'y': -6700
      map:
        x: 16
        'y': 132.5
```

Calibration points that (approximately) work for me in Firefox:
```yaml
  calibration_points:
    - vacuum:
        x: 600
        'y': -7750
      map:
        x: 243.375
        'y': 415.95
    - vacuum:
        x: -3900
        'y': 7850
      map:
        x: 125.375
        'y': 11.8
    - vacuum:
        x: 550
        'y': 8050
      map:
        x: 241.9
        'y': 8.85
    - vacuum:
        x: -6750
        'y': -6700
      map:
        x: 47.2
        'y': 390.875
```
