### ISSUE TITLE
Vacuum doesn't start

### ISSUE THREAD

**Issue by Anisse4** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#7]
Hi 3_14,

Congrats for this developpment, and thanks for sharing it.

I have installed your module following you HowTo.

Creating directories 

> /home/homeassistant/.homeassistant/www/custom_lovelace/xiaomi_vacuum_map_card

With homeassistant rights 

> drwxr-xr-x 2 homeassistant homeassistant 4.0K Aug 26 14:18 xiaomi_vacuum_map_card

Download the 3 files inside directory adding same homeassistant rights

> -rw-r--r-- 1 homeassistant homeassistant 1.1K Aug 26 09:03 style.js
> -rw-r--r-- 1 homeassistant homeassistant  442 Aug 26 09:03 texts.js
> -rw-r--r-- 1 homeassistant homeassistant  18K Aug 26 09:02 `xiaomi-vacuum-map-card.js

Added your the ressource in top of my ui-lovelace.yaml
```
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
    type: module
```

And added in ui_lovelace.yaml the configuration

```
  - icon: mdi:robot-vacuum
    # Title of the view. Will be used as the tooltip for tab icon
    title: Interactive map
    cards:
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.xiaomi_vacuum
        map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map4.png'
        base_position:
          x: 201
          y: 283
        reference_point:
          x: 161
          y: 247
        zones:
          - [[25500, 25500, 26500, 26500]]

```

I am able to check that my coordinates are correct, as when I display the cleaning zone [[25500, 25500, 26500, 26500]], I can see the square at the right place in the map. Cf screenshot under:

Don't pay attention for the play/pause... buttons, they are only screenshot:

![Screenshot](https://user-images.githubusercontent.com/54260659/63695559-42aecb80-c819-11e9-9474-2330baeca936.png)

But When I click on start nothing happens. Same when I specify GoTo zone or new zoned cleanup.

Could you give any help please ?
Thanks in advance

**Comment by PiotrMachowski** [comment]
Hi,
Are you sure that entity id is correct? Does anything appear in HA logs?

**Comment by Anisse4** [comment]
Thanks for your quick reply.

I have tried with the 2 entities I have added in homeassistant.

With the vacuum mqtt vacuum I have this following error:

`Log Details (ERROR)
Mon Aug 26 2019 17:40:14 GMT+0200 (Central European Summer Time)
cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 334, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 356, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/mqtt/vacuum/schema_state.py", line 405, in async_send_command
    message.update(params)
TypeError: cannot convert dictionary update sequence element #0 to a sequence`


But with the entity added in the configuration.yaml named "vacuum.xiaomi_vacuum_cleaner" I have nothing in the log.

in the ui_yaml I have tried with the thwo entities

>     title: Interactive map
>     cards:
>       - type: custom:xiaomi-vacuum-map-card
>         entity: vacuum.rockrobo
>         map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map4.png'
>         base_position:
>           x: 201
>           y: 283
>         reference_point:
>           x: 161
>           y: 247
>         zones:
>           - [[25500, 25500, 26500, 26500]]
>         debug:
>           true


>     title: Interactive map
>     cards:
>       - type: custom:xiaomi-vacuum-map-card
>         entity: vacuum.xiaomi_vacuum_cleaner
>         map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map4.png'
>         base_position:
>           x: 201
>           y: 283
>         reference_point:
>           x: 161
>           y: 247
>         zones:
>           - [[25500, 25500, 26500, 26500]]
>         debug:
>           true


In my Homeassistant the 2 availables entities, for the same vacuum. I am able to launch the robot with both entities

![xiaomi_vacuum_cleaner](https://user-images.githubusercontent.com/54260659/63703723-d1c3df80-c829-11e9-819a-15edd726e0f2.png)
![rockrobo](https://user-images.githubusercontent.com/54260659/63703729-d38da300-c829-11e9-8bd6-f6c6f96b6712.png)

**Comment by Anisse4** [comment]
It seems also there are some errros writing in the sql database on the raspberry, but all devices are working properly......:

> rror saving event: <Event state_changed[L]: entity_id=vacuum.rockrobo, old_state=<state vacuum.rockrobo=cleaning; battery_level=100, battery_icon=mdi:battery, fan_speed=medium, fan_speed_list=['min', 'medium', 'high', 'max', 'mop'], cleanTime=8.6, cleanArea=412.7, cleanCount=67, last_run_stats=startTime=1566834435000, endTime=1566834436000, duration=0, area=0.0, errorCode=0, errorDescription=No error, finishedFlag=False, mainBrush=291.4, sideBrush=191.4, filter=141.4, sensor=21.4, state=docked, valetudo_state=id=8, name=Charging, friendly_name=Roborock S50, supported_features=10236 @ 2019-08-26T17:47:24.464835+02:00>, new_state=<state vacuum.rockrobo=cleaning; battery_level=100, battery_icon=mdi:battery, fan_speed=medium, fan_speed_list=['min', 'medium', 'high', 'max', 'mop'], cleanTime=8.6, cleanArea=412.7, cleanCount=67, last_run_stats=startTime=1566834435000, endTime=1566834436000, duration=0, area=0.0, errorCode=0, errorDescription=No error, finishedFlag=False, mainBrush=291.4, sideBrush=191.4, filter=141.4, sensor=21.4, state=cleaning, valetudo_state=id=5, name=Cleaning, friendly_name=Roborock S50, supported_features=10236 @ 2019-08-26T17:47:24.464835+02:00>>
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.DatabaseError: database disk image is malformed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/recorder/__init__.py", line 346, in run
>     session.flush()
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
>     self._flush(objects)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
>     raise value
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
>     flush_context.execute()
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
>     uow,
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
>     insert,
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
>     statement, params
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
>     return meth(self, multiparams, params)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
>     distilled_params,
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
>     util.raise_from_cause(sqlalchemy_exception, exc_info)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
>     raise value.with_traceback(tb)
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/srv/homeassistant/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
> [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
> [parameters: ('state_changed', '{"entity_id": "vacuum.rockrobo", "old_state": {"entity_id": "vacuum.rockrobo", "state": "cleaning", "attributes": {"battery_level": 100, "battery_ico ... (1516 characters truncated) ... -26T15:47:24.541259+00:00", "context": {"id": "dbaa62d0e55446ad981689a600b01e03", "parent_id": null, "user_id": "c6b2363233a6474cab9e598c9c429115"}}}', 'LOCAL', '2019-08-26 15:47:24.541373', '2019-08-26 15:47:29.220022', 'dbaa62d0e55446ad981689a600b01e03', 'c6b2363233a6474cab9e598c9c429115')]
> (Background on this error at: http://sqlalche.me/e/4xp6)


For informatio I am not running out of space
```
pi@raspberrypi:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G  3.4G   24G  13% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   47M  417M  11% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   40M  214M  16% /boot
tmpfs            93M     0   93M   0% /run/user/1000

```

**Comment by PiotrMachowski** [comment]
MQTT vacuum is definitely not supported by this card, so we can already skip on `vacuum.rockrobo`.
Can you use service `vacuum.xiaomi_clean_zone` for entity `vacuum.xiaomi_vacuum_cleaner`?

Now I also saw that you have a small configuration issue for debug mode. Corrected config:
```
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.rockrobo
    map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map4.png'
    base_position:
      x: 201
      y: 283
    reference_point:
      x: 161
      y: 247
    zones:
      - [[25500, 25500, 26500, 26500]]
    debug: true
```

**Comment by Anisse4** [comment]
Ok so I will try only with the entity without mqtt.

Yes I am able to use the service from HA interface:

![cleanzone](https://user-images.githubusercontent.com/54260659/63706143-fbcbd080-c82e-11e9-91dd-90454002af46.png)

The robot starts his cleaning following this command.

Thanks for the correction on debug: true

**Comment by Anisse4** [comment]
For information I have no more errors on sqlite database. I've dump it and restored, no more errors on log file

**Comment by PiotrMachowski** [comment]
Does any errors appear in browsers console?

**Comment by Anisse4** [comment]
nothing related to vacuum

![image](https://user-images.githubusercontent.com/54260659/63706722-6e897b80-c830-11e9-9fd0-4a5d8782cc7e.png)

**Comment by PiotrMachowski** [comment]
This is HA log, to open browsers console you have to press `[F12]`

**Comment by Anisse4** [comment]
Here is the error displaying

![image](https://user-images.githubusercontent.com/54260659/63708005-95957c80-c833-11e9-9198-ed301e767145.png)

**Comment by PiotrMachowski** [comment]
Thank you, now I know everything I need to fix this issue.

**Comment by Anisse4** [comment]
Thank to you !
You've made a great job, can't wait to to uograde to version fixing this issue

**Comment by PiotrMachowski** [comment]
Issue should be fixed right now

**Comment by Anisse4** [comment]
Thanks for you correction and updates. Unfortunetly not yet fixed.
Before I had the error when I loaded the page and when I clicked on the button start.

Now I have the error only when I first load the page. But on the start button click no more error, but the vacuum doesn;' move.

Here is the same error on the first page load
![image](https://user-images.githubusercontent.com/54260659/63724437-fc2c9180-c857-11e9-8faa-0a311ab2d6a6.png)

And here is when I try to launch one start action 
![image](https://user-images.githubusercontent.com/54260659/63724486-16ff0600-c858-11e9-9847-69f2a2aa313f.png)

Nothing in the homeassistant log except for my xiaomi fan:

```
Mon Aug 26 2019 23:09:55 GMT+0200 (heure d’été d’Europe centrale)
You are using a custom integration for xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

```

**Comment by Anisse4** [comment]
Of course I have downloaded again the three files of the card from a wget with same address as your HowTo

**Comment by PiotrMachowski** [comment]
You have to clean browsers cache for HA

**Comment by Anisse4** [comment]
I have deleted all cache images and files, deleted all cookies history, changed to another pc. Erros are not displayed anymore but vacuum doesn't launch.

![image](https://user-images.githubusercontent.com/54260659/63758220-bdc8be00-c8bb-11e9-8b20-27528ed0ef8e.png)

![image](https://user-images.githubusercontent.com/54260659/63758289-d46f1500-c8bb-11e9-88dc-f7b432faa04d.png)

**Comment by PiotrMachowski** [comment]
Can you try again with the latest version (just updated)?

**Comment by Anisse4** [comment]
yep

**Comment by Anisse4** [comment]
Same error as previously and no start from vacuum.
I have deleted cache also

![image](https://user-images.githubusercontent.com/54260659/63759684-3761ab80-c8be-11e9-8998-826a16a096ea.png)

**Comment by Anisse4** [comment]
Tell me if it woul help to give you a username to have directly access to my HA. I have internet access with reverse proxy nginx

**Comment by PiotrMachowski** [comment]
It seems that error is deeper than I thought. I should be able to reproduce this error on my dev environment.

**Comment by Anisse4** [comment]
ok thanks. Do not hesitate if you need further information

**Comment by Maximus97** [comment]
I am having the same issue I think, none of the three commands (Go-to, Zones and Zoned cleanup) starts the robot vacuum. This card https://github.com/benct/lovelace-xiaomi-vacuum-card works fine for me so I don't think there is anything wrong with my setup.

Btw, thanks for sharing this amazing card.

**Comment by PiotrMachowski** [comment]
I had to remove long-press as it was responsible for all the issues. I have now a way to reproduce this issue locally, so hopefully it will be added again when I will figure it out.

Could you confirm that everything is working right now?

**Comment by Anisse4** [comment]
Thanks for your efforts. I'll give it a try right now

**Comment by Anisse4** [comment]
It's a little bit improving but not yet there.
No more errors on browser debug; and I have a dialog box that shows the coordinates of the task I have selected to start. But vacuum still doesn't move

![image](https://user-images.githubusercontent.com/54260659/63892145-337d7880-c9e7-11e9-85b5-c853e2a9b4fc.png)

**Comment by Anisse4** [comment]
I have to go, I'll connect tomorrow evening GMT time.

Thanks for you work, you will move this vacuum soon ;)

For Information I have Valetudo on my HA working properly when launching vacuum action from another card

**Comment by PiotrMachowski** [comment]
This behavior is exactly as expected. Previously after holding `Start` button a popup was displayed, but vacuum was not triggered. Right now I have removed long-press, so only popup will be shown if you have debug mode enabled. To disable popups and enable interactions with a vacuum you have to disable debug.

**Comment by Anisse4** [comment]
Ok I understund. Thanks for this great job, I have quickly made a test this morning, the Vacuum has moved to the target point.

So congratulations for all your work on this card and this bug.
Do you want me to close this issue or let it open until long click is available ?

**Comment by PiotrMachowski** [comment]
Great! You can close this issue, I will open a new one by myself

**Comment by Anisse4** [comment]
👍

**Comment by Anisse4** [comment]
Hi,

thanks again for your work, I've just paid you a coffe ;)
Cheers,
Anisse

**Comment by PiotrMachowski** [comment]
Hi Anisse,
Thank you very much!
Piotr
